version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  backend:
    build:
      context: ./backend_App
    container_name: backend_app_container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/mydatabase?authSource=admin
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app_network
    volumes:
      - ./backend_App:/usr/src/app

networks:
  app_network:

volumes:
  mongodb_data:
  mongodb_config: